version: '2'
services:

  database:
      image: mysql:5.5
      container_name: eazyshare_mysql
      restart: always
      ports :
       - 3307:3306
      environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=eazyshare
       - MYSQL_USER=eazyshare
       - MYSQL_PASSWORD=password
      volumes:
       - ./data:/var/lib/mysql

  eazyshare:
      build: .
      container_name: eazyshare_web
      restart: always
      ports :
       - 81:80
      environment:
       - MYSQL_HOST=database
       - MYSQL_PORT=3306
       - MYSQL_DATABASE=eazyshare
       - MYSQL_USER=eazyshare
       - MYSQL_PASSWORD=password
      volumes:
       - ./config:/usr/src/app/config
       - ./share:/share
      links:
       - database